function createfigure
%CREATEFIGURE

%  Auto-generated by MATLAB on 28-Nov-2023 14:05:58

% Create figure
figure;

% Create axes
axes1 = axes;

% Create matlab.graphics.animation.AnimatedLine
matlab.graphics.animation.AnimatedLine('DisplayName','temperatura',...
    'LineWidth',1.5,...
    'Color',[0 0 1]);

% Create ylabel
ylabel('Temperatura');

% Create xlabel
xlabel('Tempo');

% Create title
title('Controlador de Temperatura');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.271186032522527 4.08122436883092]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[22.6900161957033 22.7034252237176]);
